spring.application.name=SG_Predictor
spring.datasource.url=jdbc:postgresql://db.psyqxrrjfmrelslqodpu.supabase.co:5432/postgres?user=postgres&password=!Ssalssal7777
spring.datasource.username=postgres
spring.datasource.password=!Ssalssal7777