spring.application.name=SG_Predictor
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.defer-datasource-initialization=true
spring.config.import=optional:configtree:/run/secrets/

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/sg_predictor?sslmode=disable}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:sg_predictor_user}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:mKMfTZinnwSscMwzc8jF08T3J2PMCYUr}
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.datasource.hikari.maximum-pool-size=2
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.initialization-fail-timeout=60000

server.port=${PORT:8080}
