spring.application.name=SG_Predictor
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.defer-datasource-initialization=true
spring.config.import=optional:configtree:/run/secrets/